/*
 * Transportation Cost Management API
 *
 * 교통비 관리용 OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DailyRegisterResponse struct {

	// 유저 아이디
	UserId string `json:"userId,omitempty"`

	// 입력 날짜
	Date string `json:"date,omitempty"`

	// 교통비 등록번호
	RegisterNumber interface{} `json:"registerNumber,omitempty"`
}
