/*
 * Transportation Cost Management API
 *
 * 교통비 관리용 OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DailyFeeInfo struct {

	// 유저 아이디
	UserId string `json:"userId"`

	// 입력 날짜
	Date string `json:"date"`

	// 출발 지점
	StartPoint string `json:"startPoint,omitempty"`

	// 목적지
	Destination string `json:"destination"`

	Reason string `json:"reason,omitempty"`

	// 요금
	Fee int32 `json:"fee"`
}
