/*
 * Transportation Cost Management API
 *
 * 교통비 관리용 OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RegisterDailyFee - 일별 교통비 추가
func RegisterDailyFee(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SearchDailyFee - 일별 교통비 1건 검색
func SearchDailyFee(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
